name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Firebird
      run: |
        sudo apt install firebird3.0-server -y
        sudo cp attic/firebird.conf /etc/firebird/3.0
        sudo systemctl restart firebird3.0
        sudo chmod 0664 /etc/firebird/3.0/SYSDBA.password
        grep '=' /etc/firebird/3.0/SYSDBA.password |sed 's/^/export /' >test_user.env
    - name: Set up Erlang
      uses: actions/setup-erlang@v1
      with:
        otp-version: '22.3' # Define the OTP version [required]
    - name: Run tests
      run: |
        source test_user.env
        rebar3 eunit
