name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-16.04

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Set up Firebird
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq firebird2.5-super firebird2.5-dev
        sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
        cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
        sudo service firebird2.5-super start
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
